### ISSUE TITLE
Remote File Sync - Report Extension Bug

### ISSUE THREAD

**Issue by aolauf** [katorymnd/remote-file-sync-docs#1]
### Hello! I'am aolauf! 

```
I found a bug in my extension.

Unable to establish FTP connection.
```

**Comment by katorymnd** [comment]
> ### Hello! I'am aolauf!
> 
> ```
> I found a bug in my extension.
> 
> Unable to establish FTP connection.
> ```

This is not a bug. The issue occurs when you attempt to connect using any protocol, specifically FTP in this case, without having saved credentials.

To resolve this, you need to first initialize the connection by entering and saving your FTP credentials. Please refer to the instructions in the [usage guide](https://github.com/katorymnd/remote-file-sync-docs/blob/master/docs/usage.md) for the steps to set up the initial connection.

If you have already done that, re-initialize the connection will solve the problem.
